// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuqrmbppuugputkmjkja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1cXJtYnBwdXVncHV0a21qa2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzA5MzgsImV4cCI6MjA2NDUwNjkzOH0.0U5oWTtRlSGXeQZVAKJ0dKqglBtA2UsOJtfkOM8b1GQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);